#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Tue Feb 19 14:08:15 2013

import wx

# begin wxGlade: extracode
from wx_mpl_dynamic_graph import PanelBoundControlBox 
from wx_mpl_dynamic_graph import PanelBoundControlBox 
from wx_mpl_dynamic_graph import PanelBoundControlBox 
from wx_mpl_dynamic_graph import PanelBoundControlBox 
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.plotpanel = wx.Panel(self, -1)
        self.static_line_1 = wx.StaticLine(self, -1)
        self.ControlBoxXMax = PanelBoundControlBox(self, -1, "X max", 10)
        self.ControlBoxXMin = PanelBoundControlBox(self, -1, "X min", 0)
        self.ControlBoxYMax = PanelBoundControlBox(self, -1, "Y max", 10)
        self.ControlBoxYMin = PanelBoundControlBox(self, -1, "Y min", 0)
        self.button_quit = wx.Button(self, -1, "Quit")
        
        # Menu Bar
        self.menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "&Save", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.NewId(), "E&xit", "", wx.ITEM_NORMAL)
        self.menubar.Append(wxglade_tmp_menu, "&File")
        self.SetMenuBar(self.menubar)
        # Menu Bar end
        self.statusbar = self.CreateStatusBar(1, 0)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnQuitButtonClick, self.button_quit)
        self.Bind(wx.EVT_MENU, self.OnFileSave, id=-1)
        self.Bind(wx.EVT_MENU, self.OnFileExit, id=-1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.statusbar.SetStatusWidths([-1])
        # statusbar fields
        statusbar_fields = ["Welcome"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        canvassizer = wx.BoxSizer(wx.HORIZONTAL)
        self.plotpanel.SetSizer(canvassizer)
        sizer_3.Add(self.plotpanel, 1, wx.EXPAND, 0)
        sizer_3.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_4.Add(self.ControlBoxXMax, 1, 0, 0)
        sizer_4.Add(self.ControlBoxXMin, 1, 0, 0)
        sizer_4.Add(self.ControlBoxYMax, 1, 0, 0)
        sizer_4.Add(self.ControlBoxYMin, 1, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.ALIGN_BOTTOM, 0)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_quit, 0, wx.ALIGN_RIGHT, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

    def OnQuitButtonClick(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnQuitButtonClick' not implemented!"
        event.Skip()

    def OnFileSave(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnFileSave' not implemented!"
        event.Skip()

    def OnFileExit(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler `OnFileExit' not implemented!"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    wxk8055 = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, -1, "")
    wxk8055.SetTopWindow(frame_1)
    frame_1.Show()
    wxk8055.MainLoop()
